<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>syntax highlighting for reStructuredText http://docutils.sourceforge.net, based on rst mode from jEdit</string>
	<key>fileTypes</key>
	<array>
		<string>rst</string>
		<string>rest</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>reStructuredText Improved</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>anonymous-ref</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(__)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.ref.start</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.restructuredtext.ref</string>
			<key>end</key>
			<string>^(?!\1[\x{00000020}\t]+\S)</string>
		</dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#option-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockquote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doctest-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#refdef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substdef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#anonymous-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#footnote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list-unnumbered</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list-numbered</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#headline-or-term</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#headline-with-overline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paragraph</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preformatted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>whitespace-line</string>
				</dict>
			</array>
		</dict>
		<key>blockquote</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.blockquote-author.restructuredtext</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.blockquote-author.restructuredtext</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[\x{00000020}\t]+(--)\s+(.*)</string>
			<key>name</key>
			<string>meta.block.blockquote.author.restructuredtext</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(\.\.)\s+</string>
			<key>end</key>
			<string>^(?!\1[\x{00000020}\t])</string>
			<key>name</key>
			<string>comment.block.dot.double</string>
		</dict>
		<key>continuation</key>
		<dict>
			<key>match</key>
			<string>\\$</string>
			<key>name</key>
			<string>punctuation.separator.continuation.restructuredtext</string>
		</dict>
		<key>directive</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(\.\.)\s+([\w\-]+(?::[\w\-]+)*)(::)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.directive</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.restructuredtext.directive</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.directive</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.restructuredtext.directive.parameter</string>
			<key>end</key>
			<string>^(?:(?!\1[\x{00000020}\t])|(?=\1[\x{00000020}\t]+:|\s*$))</string>
		</dict>
		<key>doctest-block</key>
		<dict>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(&gt;&gt;&gt;)\x{00000020}(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.doctest.ps1.restructuredtext</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.doctest.ps1.restructuredtext</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1(&gt;&gt;&gt;|\.\.\.|\S))</string>
			<key>name</key>
			<string>meta.block.doctest.block.restructuredtext</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.doctest.ps1.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.doctest.ps1.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(&gt;&gt;&gt;)\x{00000020}(.*)</string>
					<key>name</key>
					<string>meta.line.doctest.ps1.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.doctest.ps2.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.doctest.ps2.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(\.\.\.)\x{00000020}(.*)</string>
					<key>name</key>
					<string>meta.line.doctest.ps1.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.doctest.expected.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(\S.*)</string>
					<key>name</key>
					<string>meta.line.doctest.expected.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>footnote</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(\.\.\s\[)(\#[\w\-]*|\*|[\w\-]+)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.ref.start</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.class.restructuredtext.ref</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.ref.end</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.restructuredtext.ref</string>
			<key>end</key>
			<string>^(?!\1[\x{00000020}\t]+\S)</string>
		</dict>
		<key>headline-or-term</key>
		<dict>
			<key>begin</key>
			<string>(?x) ^ (?= (\S+\x{00000020})* \S+ $) (?= (?!\d[\.\)]) \w .{2,55} (?&lt;!\.|::|\\|\x{00000020}) $)</string>
			<key>contentName</key>
			<string>markup.heading.headline.or-term.restructuredtext</string>
			<key>end</key>
			<string>(?x) ^ (?=[\x{00000020}\t]+\S) | ^ ( ([=\-`:.'"~^_*+\#])\2{2,55} | \s* | (?=\|\s*$) )$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.heading.restructuredtext</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>headline-with-overline</key>
		<dict>
			<key>begin</key>
			<string>^((?!::$)([=\-`:.'"~^_*+\#])\2+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.heading.restructuredtext</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.headline.restructuredtext</string>
			<key>end</key>
			<string>^((\1)|\s*)$</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.heading.restructuredtext</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-specials</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|[^|\s]+\|</string>
					<key>name</key>
					<string>variable.other.substitution.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.group</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.ref.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.group</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link-explicit</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.other.ref.restructuredtext</string>
					<key>match</key>
					<string>(`)([^`&lt;]+)(`)(__?)\b</string>
					<key>name</key>
					<string>meta.restructuredtext.link-explicit</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(`)(?=[^`&lt;]+&lt;[^&gt;]+&gt;`__?\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.group</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.other.ref.restructuredtext</string>
					<key>end</key>
					<string>(&lt;)([^&gt;]+)(&gt;)(`)(__?)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link-explicit</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link-explicit</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.restructuredtext.link-explicit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-specials</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.restructuredtext.ref</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link-explicit</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w\-]+)(__?)\b</string>
					<key>name</key>
					<string>meta.restructuredtext.link-explicit</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.group.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.ref.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.group.restructuredtext</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.link.restructuredtext</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(\#[\w\-]*|\*|[\w\-]+)(\])(_)</string>
					<key>name</key>
					<string>meta.restructuredtext.link-footnote</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(_`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.ref.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`)|^\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.ref.restructuredtext</string>
						</dict>
					</dict>
					<key>name</key>
					<string>storage.class.ref.restructuredtext</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext.implicit</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((?:^|(?&lt;=\s|["'\(\&lt;\[\{\-\/\:=\+\*]))([a-zA-Z][a-zA-Z0-9.+\-]*:(?://?)?[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}]*(?:[_~*/=+a-zA-Z0-9]|[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}](?=[&gt;]))(?:\?[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}]*(?:[_~*/=+a-zA-Z0-9]|[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}](?=[&gt;])))?(?:#[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}]*(?:[_~*/=+a-zA-Z0-9]|[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}](?=[&gt;])))?|[\-_!~*'{|}/#?^`&amp;=+$%a-zA-Z0-9\x{00000000}]+(?:\.[\-_!~*'{|}/#?^`&amp;=+$%a-zA-Z0-9\x{00000000}]+)*(?&lt;!\x{00000000})@[\-_!~*'{|}/#?^`&amp;=+$%a-zA-Z0-9\x{00000000}]+(?:\.[\-_!~*'{|}/#?^`&amp;=+$%a-zA-Z0-9\x{00000000}]*)*(?&lt;!\x{00000000})(?:[_~*/=+a-zA-Z0-9]|[\-_.!~*'()\[\];/:@&amp;=+$,%a-zA-Z0-9\x{00000000}](?=[&gt;])))(?:$|(?=\s|[\x{00000000}\.\,\;\!\?\-\/\:=\+\*"'\)\&gt;\]\}])))</string>
					<key>name</key>
					<string>string.other.link.implicit.restructuredtext</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?&lt;!`)(``)(.)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.code.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.restructuredtext.preformatted</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.restructuredtext.preformatted</string>
					<key>end</key>
					<string>(``)(?!`)|^\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.code.restructuredtext</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)(doc|ref)(:`)(?=[^`&lt;]+&lt;[^&gt;]+&gt;`)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.restructuredtext.role</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.other.ref.restructuredtext</string>
					<key>end</key>
					<string>(&lt;)([^&gt;]+)(&gt;)(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.link</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.restructuredtext.link-explicit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-specials</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.restructuredtext.role</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.restructuredtext</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)(doc|ref)(:`)([^`&lt;]*)(`)</string>
					<key>name</key>
					<string>meta.restructuredtext.link-explicit</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.restructuredtext.role</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.restructuredtext.role</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.quoted.other.restructuredtext.role</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.restructuredtext.role</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)([\w\-]+)(?:(:)([\w\-]+))?(:`)([^`]*)(`)</string>
					<key>name</key>
					<string>meta.restructuredtext.role</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\*\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bold.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\*\*)|^\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bold.restructuredtext</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.bold.restructuredtext</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>([*`])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.emph.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)|^\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.emph.restructuredtext</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.italic.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>line-block</key>
		<dict>
			<key>begin</key>
			<string>^(?=([\x{00000020}\t]*)\|[\x{00000020}\t])</string>
			<key>end</key>
			<string>^(?!\1(\|[\x{00000020}\t]|\|$|[\x{00000020}\t]))</string>
			<key>name</key>
			<string>markup.list.restructuredtext.line-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-block-content</string>
				</dict>
			</array>
		</dict>
		<key>line-block-content</key>
		<dict>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(\|)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.line-block</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^((?=\1\|)|(?!\1\s))</string>
			<key>name</key>
			<string>meta.block.restructuredtext.line-block-line</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>list-numbered</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x) [\x{00000020}\t]* (\()((?i)iii|ii|iv|ix|i|viii|vii|vi|v|x|\w)(\)) \s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.unnumbered-list.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.numeration.restructuredtext</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.unnumbered-list.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.list.numbered.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x) [\x{00000020}\t]* ((?i)iii|ii|iv|ix|i|viii|vii|vi|v|x|\w)([\.\)]) \s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.numeration.restructuredtext</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.unnumbered-list.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.list.numbered.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>list-unnumbered</key>
		<dict>
			<key>begin</key>
			<string>(?x) [\x{00000020}\t]* ([\*\+\-•‣\⁃]) \s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.unnumbered-list.restructuredtext</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.list.unnumbered.restructuredtext</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>option-list</key>
		<dict>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)((?:--?|/)\w(?:(?!\x{00000020}\x{00000020}).)*)(?=\x{00000020}\x{00000020}+\S|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.option.restructuredtext</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^((?!\1[\x{00000020}\t]+)|$)</string>
			<key>name</key>
			<string>meta.documentation.option-list.restructuredtext</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>paragraph</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x) ^ (?=\S.*\w)</string>
					<key>end</key>
					<string>(?x) ^ (?!\S) | ^ (?=[\W\s]*$) | (?=::$)</string>
					<key>name</key>
					<string>meta.paragraph.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?x) ^ (?=([\x{00000020}\t]+)\S)</string>
					<key>end</key>
					<string>(?x) (?=::$) | $</string>
					<key>name</key>
					<string>meta.paragraph.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(:)([^:]+)(:)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.restructuredtext</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.parameter</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1[\x{00000020}\t]+|$))</string>
			<key>name</key>
			<string>meta.variable.parameter</string>
		</dict>
		<key>preformatted</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>(::)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.reStructuredText</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=.)</string>
			<key>name</key>
			<string>meta.preformatted.restructuredtext</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#preformatted-content</string>
				</dict>
			</array>
		</dict>
		<key>preformatted-block</key>
		<dict>
			<key>begin</key>
			<string>^(?=([\x{00000020}\t]+))</string>
			<key>end</key>
			<string>^(?!\1)</string>
			<key>name</key>
			<string>meta.preformatted.block.restructuredtext</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#preformatted-content</string>
				</dict>
			</array>
		</dict>
		<key>preformatted-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^([\x{00000020}\t]+)(?=(?:class|def) \w+(?:\(.*\))?:$)</string>
					<key>end</key>
					<string>^(?!\1|$)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.python.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.python</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^([\x{00000020}\t]+)(?=(?:class|def) \w+(?:\(.*\))?$)</string>
					<key>end</key>
					<string>^(?!\1)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.ruby.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^([\x{00000020}\t]+)(?=\&lt;[\w\-]+(?:\s+[\w\-]+="[^"]*")*\&gt;)</string>
					<key>end</key>
					<string>^(?!\1)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.html.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^([\x{00000020}\t]+)(?=function\s+[\$\w]+\(.*\))</string>
					<key>end</key>
					<string>^(?!\1)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.javascript.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^([\x{00000020}\t]+)(?=\$\()</string>
					<key>end</key>
					<string>^(?!\1)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.javascript.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^([\x{00000020}\t]+)(?=\$[\x{00000020}\t])</string>
					<key>end</key>
					<string>^(?!\1)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.shell.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#shell</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?=([\x{00000020}\t]*)&gt;)</string>
					<key>end</key>
					<string>^(?!\1&gt;)</string>
					<key>name</key>
					<string>string.unquoted.heredoc.preformatted.preformatted</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.preformatted-line.restructuredtext</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^[\x{00000020}\t]*((?:&gt;\x{00000020}?)+)</string>
							<key>name</key>
							<string>meta.preformatted.quoted.line.restructuredtext</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>refdef</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(\.\.\s+_)([^:]*)(:)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.ref.start</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.class.restructuredtext.ref</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.ref.end</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.restructuredtext.ref</string>
			<key>end</key>
			<string>^(?!\1[\x{00000020}\t]+\S)</string>
		</dict>
		<key>shell</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$)\s</string>
					<key>name</key>
					<string>keyword.operator.shell.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x) (?&lt;=[\s\(])\b(?: for | in | do | done | while | if | then |
| fi | elif | read | echo | case | esac | exit | die | printf
)\b</string>
					<key>name</key>
					<string>support.function.builtin.shell.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x) (?: \;\; | \; | \[\[ | \]\] | \&amp;\&amp; | \|\| | \! | &gt; | &lt; | &amp; | \| )</string>
					<key>name</key>
					<string>keyword.operator.shell.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x) (?&lt;=[\s\(])\b(?: cp | mv | rm | cat | ls | \[ | \] | find | grep | awk | perl | mkdir
| rmdir | cd | cwd | pwd | svn | git | hg | scp | make | ps
| sed | python | ruby
)\b</string>
					<key>name</key>
					<string>support.function.shell.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x) (?&lt;=\s)(?: \-[\w\-]+ )</string>
					<key>name</key>
					<string>entity.other.attribute-name.shell.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\n</string>
					<key>name</key>
					<string>punctuation.separator.continuation.shell.restructuredtext</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#shell-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#shell-quoted-string</string>
				</dict>
			</array>
		</dict>
		<key>shell-quoted-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)"</string>
					<key>end</key>
					<string>(?x)"</string>
					<key>name</key>
					<string>string.quoted.double.shell.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#shell-variable</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.shell.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.entity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>shell-variable</key>
		<dict>
			<key>begin</key>
			<string>(\$\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.restructuredtext</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end.restructuredtext</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.interpolated.variable.sublime-zconf</string>
		</dict>
		<key>string-specials</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>constant.constant.character.entity.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>substdef</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>^([\x{00000020}\t]*)(\.\.)\s(\|[\w\-]+\|)\s([^:]+)(::)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.directive</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.substitution.restructuredtext</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.restructuredtext.directive</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.restructuredtext.directive</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.restructuredtext.subst</string>
			<key>end</key>
			<string>^(?!\1[\x{00000020}\t]+\S)</string>
		</dict>
		<key>table</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?=([\x{00000020}\t]*)(\+\-+)+\+\s*)</string>
					<key>end</key>
					<string>^(?!\1(\+|\|))</string>
					<key>name</key>
					<string>meta.block.table.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#table-content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(==+\x{00000020}+)+==+$</string>
					<key>name</key>
					<string>keyword.operator.table.row.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(--+\x{00000020}+)+--+$</string>
					<key>name</key>
					<string>keyword.operator.table.row.restructuredtext</string>
				</dict>
			</array>
		</dict>
		<key>table-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(\+\-+)+\+</string>
					<key>name</key>
					<string>keyword.operator.table.row.restructuredtext</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[\x{00000020}\t]*(\+=+)+\+</string>
					<key>name</key>
					<string>keyword.operator.table.row.restructuredtext</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\|(?=[\x{00000020}\t]))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.table.data.restructuredtext</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\s)(?=\|)</string>
					<key>name</key>
					<string>meta.block.table.data.restructuredtext</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\|$</string>
					<key>name</key>
					<string>keyword.operator.table.data.restructuredtext</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>test_text.restructuredtext</string>
	<key>uuid</key>
	<string>62DA9AD6-36E1-4AB7-BB87-E933AD9FD1A4</string>
</dict>
</plist>