# Code to generate values:
from kivy.uix.widget import Widget
from kivy.properties import *
from kivy.graphics.transformation import *
from kivy.uix.screenmanager import *
import inspect

def ImportModule(modname):
    result = __import__(modname)
    for i in modname.split('.')[1:]:
        result = getattr(result, i)
    return result

def get_default(prop):
    if isinstance(prop, tuple):
        return tuple(get_default(x) for x in prop)

    if hasattr(prop, 'defaultvalue'):
        return get_default(prop.defaultvalue)

    if isinstance(prop, Matrix):
        return 'Matrix'

    if isinstance(prop, SwapTransition):
        return 'SwapTransition'

    if inspect.isclass(prop) or inspect.isfunction(prop):
        return prop.__name__
    return prop


import kivy
import os
from kivy import uix

class_to_members = {}

for f in os.listdir(os.path.dirname(uix.__file__)):
    if f.endswith('.py'):
        modname = 'kivy.uix.' + f[:-3]
        mod = ImportModule(modname)
        for widget_name in sorted(dir(mod)):
            widget = getattr(mod, widget_name)
            try:
                if not issubclass(widget, Widget):
                    continue
            except:
                pass
            else:
                props = []
                for prop_name in dir(widget):
                    if not prop_name.startswith('_'):
                        prop = getattr(widget, prop_name)
                        if prop.__class__.__name__.endswith('Property'):
                            default_val = get_default(prop)
                            props.append((prop_name, default_val))

                class_to_members[widget_name] = sorted(props)



from pprint import pprint

# print '{'
# for c, members in sorted(class_to_members.iteritems()):
#     print '%r:%r,' % (c, members)
# print '}'


from types import NoneType
from pprint import pprint

class_to_members = \
{
'AbstractView':[('adapter', None), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Accordion':[('anim_duration', 0.25), ('anim_func', 'out_expo'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('min_space', '44dp'), ('opacity', 1.0), ('orientation', 'horizontal'), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'AccordionItem':[('accordion', None), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('background_selected', 'atlas://data/images/defaulttheme/button_pressed'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('collapse', True), ('collapse_alpha', 1.0), ('container', None), ('container_title', None), ('content_size', [100, 100]), ('height', 100), ('id', None), ('ids', {}), ('min_space', '44dp'), ('opacity', 1.0), ('orientation', 'vertical'), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('title', ''), ('title_args', {}), ('title_template', 'AccordionItemTitle'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'AnchorLayout':[('anchor_x', 'center'), ('anchor_y', 'center'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('padding', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'AsyncImage':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'BoxLayout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', 0), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Bubble':[('arrow_image', 'atlas://data/images/defaulttheme/bubble_arrow'), ('arrow_pos', 'bottom_mid'), ('background_color', [1, 1, 1, 1]), ('background_image', 'atlas://data/images/defaulttheme/bubble'), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('limit_to', None), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'BubbleButton':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'BubbleContent':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Button':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'Camera':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('index', -1), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('play', True), ('pos', (0, 0)), ('pos_hint', {}), ('resolution', [-1, -1]), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Carousel':[('anim_cancel_duration', 0.3), ('anim_move_duration', 0.5), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('current_slide', None), ('direction', 'right'), ('height', 100), ('id', None), ('ids', {}), ('index', None), ('loop', False), ('min_move', 0.2), ('next_slide', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('previous_slide', None), ('right', None), ('scroll_distance', '20dp'), ('scroll_timeout', 200), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('slides', []), ('slides_container', None), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'CheckBox':[('active', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('group', None), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'CodeInput':[('auto_indent', False), ('background_active', 'atlas://data/images/defaulttheme/textinput_active'), ('background_color', [1, 1, 1, 1]), ('background_normal', 'atlas://data/images/defaulttheme/textinput'), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('cursor', None), ('cursor_blink', False), ('cursor_col', None), ('cursor_pos', None), ('cursor_row', None), ('focus', False), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('foreground_color', [0, 0, 0, 1]), ('height', 100), ('hint_text', ''), ('hint_text_color', [0.5, 0.5, 0.5, 1.0]), ('id', None), ('ids', {}), ('lexer', None), ('line_height', 1), ('multiline', True), ('opacity', 1.0), ('padding', [6, 6, 6, 6]), ('padding_x', [0, 0]), ('padding_y', [0, 0]), ('parent', None), ('password', False), ('pos', (0, 0)), ('pos_hint', {}), ('readonly', False), ('right', None), ('scroll_x', 0), ('scroll_y', 0), ('selection_color', [0.1843, 0.6549, 0.8313, 0.5]), ('selection_from', None), ('selection_text', ''), ('selection_to', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('tab_width', 4), ('text', None), ('top', None), ('use_bubble', False), ('width', 100), ('x', 0), ('y', 0)],
'ColorPicker':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', (1, 1, 1, 1)), ('font_name', 'data/fonts/DroidSansMono.ttf'), ('foreground_color', (1, 1, 1, 1)), ('height', 100), ('hex_color', None), ('hsv', (1, 1, 1)), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('wheel', None), ('width', 100), ('x', 0), ('y', 0)],
'ColorWheel':[('a', 0), ('b', 0), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', (0, 0, 0, 0)), ('g', 0), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('r', 0), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'CompositeListItem':[('background_color', [1, 1, 1, 1]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('deselected_color', [0.33, 0.33, 0.33, 1]), ('height', 100), ('id', None), ('ids', {}), ('index', -1), ('is_selected', False), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('representing_cls', None), ('right', None), ('selected_color', [1.0, 0.0, 0.0, 1]), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', 0), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'DropDown':[('attach_to', None), ('auto_width', True), ('bar_alpha', 1.0), ('bar_color', [0.7, 0.7, 0.7, 0.9]), ('bar_margin', 0), ('bar_width', '2dp'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('container', None), ('dismiss_on_select', True), ('do_scroll', None), ('do_scroll_x', True), ('do_scroll_y', True), ('effect_cls', 'DampedScrollEffect'), ('effect_x', None), ('effect_y', None), ('hbar', None), ('height', 100), ('id', None), ('ids', {}), ('max_height', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('scroll_distance', 20.0), ('scroll_timeout', 250), ('scroll_x', 0.0), ('scroll_y', 1.0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('vbar', None), ('viewport_size', [0, 0]), ('width', 100), ('x', 0), ('y', 0)],
'FileChooserController':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('dirselect', False), ('file_encodings', ['utf-8', 'latin1', 'cp1252']), ('files', []), ('filter_dirs', False), ('filters', []), ('height', 100), ('id', None), ('ids', {}), ('multiselect', False), ('opacity', 1.0), ('parent', None), ('path', u'/'), ('pos', (0, 0)), ('pos_hint', {}), ('progress_cls', 'FileChooserProgress'), ('right', None), ('rootpath', None), ('selection', []), ('show_hidden', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('sort_func', 'alphanumeric_folders_first'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'FileChooserIconView':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('dirselect', False), ('file_encodings', ['utf-8', 'latin1', 'cp1252']), ('files', []), ('filter_dirs', False), ('filters', []), ('height', 100), ('id', None), ('ids', {}), ('multiselect', False), ('opacity', 1.0), ('parent', None), ('path', u'/'), ('pos', (0, 0)), ('pos_hint', {}), ('progress_cls', 'FileChooserProgress'), ('right', None), ('rootpath', None), ('selection', []), ('show_hidden', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('sort_func', 'alphanumeric_folders_first'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'FileChooserListView':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('dirselect', False), ('file_encodings', ['utf-8', 'latin1', 'cp1252']), ('files', []), ('filter_dirs', False), ('filters', []), ('height', 100), ('id', None), ('ids', {}), ('multiselect', False), ('opacity', 1.0), ('parent', None), ('path', u'/'), ('pos', (0, 0)), ('pos_hint', {}), ('progress_cls', 'FileChooserProgress'), ('right', None), ('rootpath', None), ('selection', []), ('show_hidden', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('sort_func', 'alphanumeric_folders_first'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'FileChooserProgress':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('index', 0), ('opacity', 1.0), ('parent', None), ('path', ''), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('total', 1), ('width', 100), ('x', 0), ('y', 0)],
'FileChooserProgressBase':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('index', 0), ('opacity', 1.0), ('parent', None), ('path', ''), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('total', 1), ('width', 100), ('x', 0), ('y', 0)],
'FloatLayout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'GridLayout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Image':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Label':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'Layout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'ListItemButton':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('deselected_color', [0.0, 1.0, 0.0, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('index', -1), ('is_selected', False), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('selected_color', [1.0, 0.0, 0.0, 1]), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'ListItemLabel':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('index', -1), ('is_selected', False), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'ListView':[('adapter', None), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('container', None), ('divider', None), ('divider_height', 2), ('height', 100), ('id', None), ('ids', {}), ('item_strings', []), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_height', None), ('scrolling', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'ModalView':[('anchor_x', 'center'), ('anchor_y', 'center'), ('attach_to', None), ('auto_dismiss', True), ('background', 'atlas://data/images/defaulttheme/modalview-background'), ('background_color', [0, 0, 0, 0.7]), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('padding', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Popup':[('anchor_x', 'center'), ('anchor_y', 'center'), ('attach_to', None), ('auto_dismiss', True), ('background', 'atlas://data/images/defaulttheme/modalview-background'), ('background_color', [0, 0, 0, 0.7]), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('padding', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('separator_color', [0.1843137254901961, 0.6549019607843137, 0.8313725490196079, 1.0]), ('separator_height', '2dp'), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('title', 'No title'), ('title_size', '14sp'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'ProgressBar':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('max', 100.0), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('value', None), ('value_normalized', None), ('width', 100), ('x', 0), ('y', 0)],
'RelativeLayout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstAsyncImage':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstBlockQuote':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstDefinition':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstDefinitionList':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstDefinitionSpace':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstDocument':[('anchors_widgets', []), ('bar_alpha', 1.0), ('bar_color', [0.7, 0.7, 0.7, 0.9]), ('bar_margin', 0), ('bar_width', '2dp'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('colors', {'paragraph': '202020', 'link': 'ce5c00', 'bullet': '000000', 'background': 'e5e6e9', 'title': '204a87'}), ('content', None), ('do_scroll', None), ('do_scroll_x', True), ('do_scroll_y', True), ('document_root', None), ('effect_cls', 'DampedScrollEffect'), ('effect_x', None), ('effect_y', None), ('hbar', None), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs_assoc', {}), ('right', None), ('scatter', None), ('scroll_distance', 20.0), ('scroll_timeout', 250), ('scroll_x', 0.0), ('scroll_y', 1.0), ('show_errors', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('text', None), ('title', ''), ('toctrees', {}), ('top', None), ('vbar', None), ('viewport_size', [0, 0]), ('width', 100), ('x', 0), ('y', 0)],
'RstEmptySpace':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstEntry':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstFieldBody':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstFieldList':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstFieldName':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'RstGridLayout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstImage':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstList':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstListBullet':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'RstListItem':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstLiteralBlock':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstNote':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstParagraph':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('mx', 10), ('my', 10), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'RstSystemMessage':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstTable':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstTerm':[('anchor_x', 'center'), ('anchor_y', 'center'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('padding', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstTitle':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('section', 0), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'RstTransition':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'RstVideoPlayer':[('allow_fullscreen', True), ('annotations', ''), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('container', None), ('duration', -1), ('fullscreen', False), ('height', 100), ('id', None), ('ids', {}), ('image_loading', 'data/images/image-loading.gif'), ('image_overlay_play', 'atlas://data/images/defaulttheme/player-play-overlay'), ('image_pause', 'atlas://data/images/defaulttheme/media-playback-pause'), ('image_play', 'atlas://data/images/defaulttheme/media-playback-start'), ('image_stop', 'atlas://data/images/defaulttheme/media-playback-stop'), ('image_volumehigh', 'atlas://data/images/defaulttheme/audio-volume-high'), ('image_volumelow', 'atlas://data/images/defaulttheme/audio-volume-low'), ('image_volumemedium', 'atlas://data/images/defaulttheme/audio-volume-medium'), ('image_volumemuted', 'atlas://data/images/defaulttheme/audio-volume-muted'), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('options', {}), ('padding', [0, 0, 0, 0]), ('parent', None), ('play', False), ('pos', (0, 0)), ('pos_hint', {}), ('position', 0), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', ''), ('spacing', [0, 0]), ('state', 'stop'), ('thumbnail', ''), ('top', None), ('volume', 1.0), ('width', 100), ('x', 0), ('y', 0)],
'RstWarning':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Scatter':[('auto_bring_to_front', True), ('bbox', None), ('center', None), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('do_collide_after_children', False), ('do_rotation', True), ('do_scale', True), ('do_translation', None), ('do_translation_x', True), ('do_translation_y', True), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', None), ('pos_hint', {}), ('right', None), ('rotation', None), ('scale', None), ('scale_max', 1e+20), ('scale_min', 0.01), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('transform', 'Matrix'), ('transform_inv', 'Matrix'), ('translation_touches', 1), ('width', 100), ('x', None), ('y', None)],
'ScatterLayout':[('auto_bring_to_front', True), ('bbox', None), ('center', None), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('do_collide_after_children', False), ('do_rotation', True), ('do_scale', True), ('do_translation', None), ('do_translation_x', True), ('do_translation_y', True), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', None), ('pos_hint', {}), ('right', None), ('rotation', None), ('scale', None), ('scale_max', 1e+20), ('scale_min', 0.01), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('transform', 'Matrix'), ('transform_inv', 'Matrix'), ('translation_touches', 1), ('width', 100), ('x', None), ('y', None)],
'ScatterPlane':[('auto_bring_to_front', True), ('bbox', None), ('center', None), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('do_collide_after_children', False), ('do_rotation', True), ('do_scale', True), ('do_translation', None), ('do_translation_x', True), ('do_translation_y', True), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', None), ('pos_hint', {}), ('right', None), ('rotation', None), ('scale', None), ('scale_max', 1e+20), ('scale_min', 0.01), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('transform', 'Matrix'), ('transform_inv', 'Matrix'), ('translation_touches', 1), ('width', 100), ('x', None), ('y', None)],
'Screen':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('manager', None), ('name', ''), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('transition_progress', 0.0), ('transition_state', 'out'), ('width', 100), ('x', 0), ('y', 0)],
'ScreenManager':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('current', None), ('current_screen', None), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('screen_names', None), ('screens', []), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('transition', 'SwapTransition'), ('width', 100), ('x', 0), ('y', 0)],
'ScrollView':[('bar_alpha', 1.0), ('bar_color', [0.7, 0.7, 0.7, 0.9]), ('bar_margin', 0), ('bar_width', '2dp'), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('do_scroll', None), ('do_scroll_x', True), ('do_scroll_y', True), ('effect_cls', 'DampedScrollEffect'), ('effect_x', None), ('effect_y', None), ('hbar', None), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('scroll_distance', 20.0), ('scroll_timeout', 250), ('scroll_x', 0.0), ('scroll_y', 1.0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('vbar', None), ('viewport_size', [0, 0]), ('width', 100), ('x', 0), ('y', 0)],
'SettingBoolean':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('desc', None), ('disabled', False), ('height', 100), ('id', None), ('ids', {}), ('key', None), ('opacity', 1.0), ('panel', None), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('section', None), ('selected_alpha', 0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('title', '<No title set>'), ('top', None), ('value', None), ('values', ['0', '1']), ('width', 100), ('x', 0), ('y', 0)],
'SettingItem':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('desc', None), ('disabled', False), ('height', 100), ('id', None), ('ids', {}), ('key', None), ('opacity', 1.0), ('panel', None), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('section', None), ('selected_alpha', 0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('title', '<No title set>'), ('top', None), ('value', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingNumeric':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('desc', None), ('disabled', False), ('height', 100), ('id', None), ('ids', {}), ('key', None), ('opacity', 1.0), ('panel', None), ('parent', None), ('popup', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('section', None), ('selected_alpha', 0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('textinput', None), ('title', '<No title set>'), ('top', None), ('value', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingOptions':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('desc', None), ('disabled', False), ('height', 100), ('id', None), ('ids', {}), ('key', None), ('opacity', 1.0), ('options', []), ('panel', None), ('parent', None), ('popup', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('section', None), ('selected_alpha', 0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('title', '<No title set>'), ('top', None), ('value', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingPath':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('desc', None), ('disabled', False), ('height', 100), ('id', None), ('ids', {}), ('key', None), ('opacity', 1.0), ('panel', None), ('parent', None), ('popup', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('section', None), ('selected_alpha', 0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('textinput', None), ('title', '<No title set>'), ('top', None), ('value', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingSidebarLabel':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('panel', None), ('panel_uid', -1), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('selected', False), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'SettingSpacer':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingString':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('desc', None), ('disabled', False), ('height', 100), ('id', None), ('ids', {}), ('key', None), ('opacity', 1.0), ('panel', None), ('parent', None), ('popup', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('section', None), ('selected_alpha', 0), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('textinput', None), ('title', '<No title set>'), ('top', None), ('value', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingTitle':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('title', ''), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'Settings':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('menu', None), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('selection', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', 0), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'SettingsPanel':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('config', None), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('settings', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('title', 'Default title'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Slider':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('max', 100.0), ('min', 0.0), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', 10), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('range', (0.0, 100.0)), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('step', 0), ('top', None), ('value', 0.0), ('value_normalized', None), ('value_pos', None), ('width', 100), ('x', 0), ('y', 0)],
'Spinner':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('dropdown_cls', 'DropDown'), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('is_open', False), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('option_cls', 'SpinnerOption'), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('values', []), ('width', 100), ('x', 0), ('y', 0)],
'SpinnerOption':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'Splitter':[('border', [4, 4, 4, 4]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('max_size', '500pt'), ('min_size', '100pt'), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('sizable_from', 'left'), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', 0), ('strip_cls', 'SplitterStrip'), ('strip_size', '10pt'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'SplitterStrip':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'StackLayout':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('orientation', 'lr-tb'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'StencilView':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'Switch':[('active', False), ('active_norm_pos', 0), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('touch_control', None), ('touch_distance', 0), ('width', 100), ('x', 0), ('y', 0)],
'TabbedPanel':[('background_color', [1, 1, 1, 1]), ('background_image', 'atlas://data/images/defaulttheme/tab'), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('current_tab', None), ('default_tab', None), ('default_tab_cls', 'TabbedPanelHeader'), ('default_tab_content', None), ('default_tab_text', 'Default tab'), ('do_default_tab', True), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('tab_height', '40dp'), ('tab_list', None), ('tab_pos', 'top_left'), ('tab_width', '100dp'), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'TabbedPanelContent':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'TabbedPanelHeader':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('content', None), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('group', None), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'TabbedPanelItem':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('content', None), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('group', None), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'TabbedPanelStrip':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('height', 100), ('id', None), ('ids', {}), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('tabbed_panel', None), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'TextInput':[('auto_indent', False), ('background_active', 'atlas://data/images/defaulttheme/textinput_active'), ('background_color', [1, 1, 1, 1]), ('background_normal', 'atlas://data/images/defaulttheme/textinput'), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('cursor', None), ('cursor_blink', False), ('cursor_col', None), ('cursor_pos', None), ('cursor_row', None), ('focus', False), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('foreground_color', [0, 0, 0, 1]), ('height', 100), ('hint_text', ''), ('hint_text_color', [0.5, 0.5, 0.5, 1.0]), ('id', None), ('ids', {}), ('line_height', 1), ('multiline', True), ('opacity', 1.0), ('padding', [6, 6, 6, 6]), ('padding_x', [0, 0]), ('padding_y', [0, 0]), ('parent', None), ('password', False), ('pos', (0, 0)), ('pos_hint', {}), ('readonly', False), ('right', None), ('scroll_x', 0), ('scroll_y', 0), ('selection_color', [0.1843, 0.6549, 0.8313, 0.5]), ('selection_from', None), ('selection_text', ''), ('selection_to', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('tab_width', 4), ('text', None), ('top', None), ('use_bubble', False), ('width', 100), ('x', 0), ('y', 0)],
'TextInputCutCopyPaste':[('arrow_image', 'atlas://data/images/defaulttheme/bubble_arrow'), ('arrow_pos', 'bottom_mid'), ('background_color', [1, 1, 1, 1]), ('background_image', 'atlas://data/images/defaulttheme/bubble'), ('border', [16, 16, 16, 16]), ('but_copy', None), ('but_cut', None), ('but_paste', None), ('but_selectall', None), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('content', None), ('height', 100), ('id', None), ('ids', {}), ('limit_to', None), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('orientation', 'horizontal'), ('padding', [0, 0, 0, 0]), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('spacing', [0, 0]), ('textinput', None), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'ToggleButton':[('anchors', {}), ('background_color', [1, 1, 1, 1]), ('background_down', 'atlas://data/images/defaulttheme/button_pressed'), ('background_normal', 'atlas://data/images/defaulttheme/button'), ('bold', False), ('border', [16, 16, 16, 16]), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('group', None), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('state', 'normal'), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'TreeView':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('hide_root', False), ('id', None), ('ids', {}), ('indent_level', '16dp'), ('indent_start', '24dp'), ('load_func', None), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('root', None), ('root_options', {}), ('selected_node', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
'TreeViewLabel':[('anchors', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('color_selected', [0.3, 0.3, 0.3, 1.0]), ('even_color', [0.5, 0.5, 0.5, 0.1]), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('is_leaf', True), ('is_loaded', False), ('is_open', False), ('is_selected', False), ('italic', False), ('level', -1), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('no_selection', False), ('nodes', []), ('odd', False), ('odd_color', [1.0, 1.0, 1.0, 0.0]), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('parent_node', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'VKeyboard':[('active_keys', {}), ('auto_bring_to_front', True), ('available_layouts', {}), ('background', 'atlas://data/images/defaulttheme/vkeyboard_background'), ('background_border', [16, 16, 16, 16]), ('background_color', [1, 1, 1, 1]), ('bbox', None), ('callback', None), ('center', None), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('do_collide_after_children', False), ('do_rotation', True), ('do_scale', True), ('do_translation', None), ('do_translation_x', True), ('do_translation_y', True), ('docked', False), ('font_name', 'data/fonts/DejaVuSans.ttf'), ('font_size', '20dp'), ('have_capslock', False), ('have_shift', False), ('height', 100), ('id', None), ('ids', {}), ('key_background_color', [1, 1, 1, 1]), ('key_background_down', 'atlas://data/images/defaulttheme/vkeyboard_key_down'), ('key_background_normal', 'atlas://data/images/defaulttheme/vkeyboard_key_normal'), ('key_border', [8, 8, 8, 8]), ('key_margin', [2, 2, 2, 2]), ('layout', None), ('layout_geometry', {}), ('layout_mode', 'normal'), ('layout_path', 'D:\\bin\\Kivy-1.7.2-w32\\kivy\\kivy\\data\\keyboards'), ('margin_hint', [0.05, 0.06, 0.05, 0.06]), ('opacity', 1.0), ('parent', None), ('pos', None), ('pos_hint', {}), ('right', None), ('rotation', None), ('scale', None), ('scale_max', 1e+20), ('scale_min', 0.01), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('target', None), ('top', None), ('transform', 'Matrix'), ('transform_inv', 'Matrix'), ('translation_touches', 1), ('width', 100), ('x', None), ('y', None)],
'Video':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('duration', -1), ('eos', False), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('loaded', False), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('options', {}), ('parent', None), ('play', False), ('pos', (0, 0)), ('pos_hint', {}), ('position', -1), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('state', 'stop'), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('volume', 1.0), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayer':[('allow_fullscreen', True), ('annotations', ''), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('col_default_width', 0), ('col_force_default', False), ('cols', None), ('cols_minimum', {}), ('container', None), ('duration', -1), ('fullscreen', False), ('height', 100), ('id', None), ('ids', {}), ('image_loading', 'data/images/image-loading.gif'), ('image_overlay_play', 'atlas://data/images/defaulttheme/player-play-overlay'), ('image_pause', 'atlas://data/images/defaulttheme/media-playback-pause'), ('image_play', 'atlas://data/images/defaulttheme/media-playback-start'), ('image_stop', 'atlas://data/images/defaulttheme/media-playback-stop'), ('image_volumehigh', 'atlas://data/images/defaulttheme/audio-volume-high'), ('image_volumelow', 'atlas://data/images/defaulttheme/audio-volume-low'), ('image_volumemedium', 'atlas://data/images/defaulttheme/audio-volume-medium'), ('image_volumemuted', 'atlas://data/images/defaulttheme/audio-volume-muted'), ('minimum_height', 0), ('minimum_size', (0, 0)), ('minimum_width', 0), ('opacity', 1.0), ('options', {}), ('padding', [0, 0, 0, 0]), ('parent', None), ('play', False), ('pos', (0, 0)), ('pos_hint', {}), ('position', 0), ('right', None), ('row_default_height', 0), ('row_force_default', False), ('rows', None), ('rows_minimum', {}), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', ''), ('spacing', [0, 0]), ('state', 'stop'), ('thumbnail', ''), ('top', None), ('volume', 1.0), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayerAnnotation':[('anchors', {}), ('annotation', {}), ('bold', False), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('duration', 1), ('font_name', 'DroidSans'), ('font_size', '15sp'), ('halign', 'left'), ('height', 100), ('id', None), ('ids', {}), ('italic', False), ('line_height', 1.0), ('markup', False), ('mipmap', False), ('opacity', 1.0), ('padding', (0, 0)), ('padding_x', 0), ('padding_y', 0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('refs', {}), ('right', None), ('shorten', False), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('start', 0), ('text', ''), ('text_size', [None, None]), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('valign', 'bottom'), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayerPlayPause':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('video', None), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayerPreview':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('click_done', False), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('top', None), ('video', None), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayerProgressBar':[('alpha', 1.0), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('max', 100.0), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('seek', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('value', None), ('value_normalized', None), ('video', None), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayerStop':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('video', None), ('width', 100), ('x', 0), ('y', 0)],
'VideoPlayerVolume':[('allow_stretch', False), ('anim_delay', 0.25), ('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('color', [1, 1, 1, 1]), ('height', 100), ('id', None), ('ids', {}), ('image_ratio', None), ('keep_data', False), ('keep_ratio', True), ('mipmap', False), ('nocache', False), ('norm_image_size', None), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('source', None), ('texture', None), ('texture_size', [0, 0]), ('top', None), ('video', None), ('width', 100), ('x', 0), ('y', 0)],
'Widget':[('center', (None, None)), ('center_x', None), ('center_y', None), ('children', []), ('cls', []), ('height', 100), ('id', None), ('ids', {}), ('opacity', 1.0), ('parent', None), ('pos', (0, 0)), ('pos_hint', {}), ('right', None), ('size', (100, 100)), ('size_hint', (1, 1)), ('size_hint_x', 1), ('size_hint_y', 1), ('top', None), ('width', 100), ('x', 0), ('y', 0)],
}


template_variables = {
  'bool' : ['True', 'False'],
}

template = '''
- name: '%(widget_name)s'
  description: "%(widget_name)s: %(default)s%(desc_part2)s"
  pattern: "%(widget_name)s:  %(default)s"
  icon: attribute
  match_previous_sub_scope: ['default.class', '%(parent)s']
'''

template_class = '''
- name: '%(class)s'
  description: ""
  pattern: "%(class)s"
  icon: class
'''

with open('d:/temp/out.txt', 'w') as stream:
    for class_, members in sorted(class_to_members.iteritems()):
        print >> stream, template_class % {'class':class_}

        for member_type, defaults in sorted(members):
            desc_part2 = ''
            if isinstance(defaults, bool):
                default = '${bool}'
                desc_part2 = ' (default:%s)' % (defaults,)

            elif isinstance(defaults, (str, int, float, unicode)):
                default = str(defaults)
                if default:
                    default = repr(default)

            elif isinstance(defaults, NoneType):
                default = ''

            elif isinstance(defaults, dict):
                default = '{}'

            elif isinstance(defaults, (list, tuple)):
                new_val = [str(defaults)]
                key = '%s' % (member_type,)

                if member_type in template_variables:
                    curr = template_variables[key]
                    if curr != new_val:
                        key = '%s_%s' % (class_, member_type)  #create a custom key for this type!

                template_variables[key] = new_val
                default = '${%s}' % key

            else:
                raise AssertionError('Type not handled: ' + str(defaults)+ ' '+type(defaults))

            print >>stream,template % dict(widget_name=member_type, parent=class_, default=default, desc_part2=desc_part2)

    pprint(template_variables, stream=stream)
